<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>crazy_eights.editor</AssemblyName>
		<PackageId>crazy_eights.editor</PackageId>
		<LangVersion>13</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX;ADDON;DEBUG</DefineConstants>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<DefaultItemExcludes>$(DefaultItemExcludes);**\editor\**\*;**\unittest\**\*</DefaultItemExcludes>

	</PropertyGroup>

	<ItemGroup>
		
		<None Update="**\*.cs.scss" DependentUpon="%(Filename)" />
		<Compile Update="**\*.razor.cs" DependentUpon="%(Filename)" />
		<None Update="**\*.razor.scss" DependentUpon="%(Filename)" />

	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="**/*.razor" Exclude="**\editor\**\*;**\unittest\**\*" />
	</ItemGroup>



	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalToolsNamespace" Static="true" />
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
	</ItemGroup>

  <PropertyGroup>
	<OutputPath>F:\Games\SteamLibrary\steamapps\common\sbox/.vs/output/</OutputPath>
	<DocumentationFile>F:\Games\SteamLibrary\steamapps\common\sbox/.vs/output/crazy_eights.editor.xml</DocumentationFile>
	<RootNamespace>Sandbox</RootNamespace>
	<Nullable>disable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Analyzer Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed\Sandbox.CodeUpgrader.dll"/>
		<Analyzer Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed\Sandbox.Generator.dll"/>
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.System.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Engine.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Filesystem.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Game.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Reflection.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Tools.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Compiling.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Microsoft.CodeAnalysis.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Sandbox.Bind.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/Facepunch.ActionGraphs.dll" />
		<Reference Include="F:\Games\SteamLibrary\steamapps\common\sbox\bin\managed/SkiaSharp.dll" />
	</ItemGroup>

  <ItemGroup>
		<ProjectReference Include="F:\Games\SteamLibrary\steamapps\common\sbox\editor\ActionGraph\Code\actiongraph.csproj" />
		<ProjectReference Include="E:\s&amp;box\games\sbox-crazyeights\Code\crazy_eights.csproj" />
		<ProjectReference Include="F:\Games\SteamLibrary\steamapps\common\sbox\editor\Hammer\Code\hammer.csproj" />
		<ProjectReference Include="F:\Games\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Base Editor Library.csproj" />
		<ProjectReference Include="F:\Games\SteamLibrary\steamapps\common\sbox\editor\ShaderGraph\Code\shadergraph.csproj" />

  </ItemGroup>

</Project>
